### ISSUE TITLE
duplicate 'row.names' bug

### ISSUE THREAD

**Issue by alex-wenzel** [ACastanza/GSEA_R#5]
Error text

```
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning messages:
1: package ‘dplyr’ was built under R version 3.5.2 
2: non-unique values when setting 'row.names': ‘HALLMARK_E2F_TARGETS’, ‘HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION’, ‘HALLMARK_GLYCOLYSIS’, ‘HALLMARK_MITOTIC_SPINDLE’, ‘HALLMARK_PEROXISOME’, ‘HALLMARK_TGF_BETA_SIGNALING’ 
```

I ran this twice and the gene sets it listed as having non-unique `row.names` changed. The most recent normal stdout print before the error was `[1] "set name=" "test" `. 

- [GCT](https://drive.google.com/file/d/1ukYzOSrcEzNiVBPorskML907u5o5cO-m/view?usp=sharing)
- [CLS](https://drive.google.com/file/d/19BGm45shgd2zmvR7b8Z-GyX85zvDdAs5/view?usp=sharing)
- [GMT](https://drive.google.com/file/d/1gh1bIZJRK9lde14OocOQk69e_H5oXDFn/view?usp=sharing)

Other parameters

> collapse: no
> Permutation: gene_set
> override permutations: no
> override max gene set: no
> override min gene set: no

I am using R 3.5.1. Happy to try to upgrade and try 3.5.2 if the solution isn't clear otherwise.

**Comment by alex-wenzel** [comment]
Here's the `traceback()`

```
> traceback()
9: stop("duplicate 'row.names' are not allowed")
8: `.rowNamesDF<-`(x, value = value)
7: `row.names<-.data.frame`(`*tmp*`, value = set.table.phen1[1:max.sets.phen1, 
       2])
6: `row.names<-`(`*tmp*`, value = set.table.phen1[1:max.sets.phen1, 
       2]) at GSEA.1.0.R#2182
5: GSEA.Analyze.Sets(directory = outdir, topgs = 20, height = 16, 
       width = 16) at Run.GSEA.R#105
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("Run.GSEA.R")
```

Yes, the only GMT I'm using is v7.0 hallmarks. I also just tried with the same files and parameters except for using phenotype permutations, and I still got the same error.

**Comment by ACastanza** [comment]
I attempted this again, using the P53 dataset instead of my typical choice of the leukemia dataset, with gene_set permutations, the 7.0 Hallmarks Symbols GMT and I used a PC instead of my standard Mac. I'm still not able to reproduce this bug. This may be an issue in that version of R, my systems are all running 3.6.1
